### ISSUE TITLE
bindkey C-u and C-d for page up and down

### ISSUE THREAD

**Issue by ztlevi** [Vifon/deer#24]
How to bind the C-u and C-d for page up and down?
Currently I have
``` shell
DEER_KEYS[page_up]='^U'
DEER_KEYS[page_down]='^D'
```
But it's not working...
Thanks

**Comment by Vifon** [comment]
Short answer: Currently you can't.

Long answer: It won't work. With the way currently things work, only a single-character keys are supported. Page up/down generates a multi-character sequence. It possibly could be helped if deer used a regular zsh keymap (only a theory) but I won't have the time to look into it anytime soon.

I'll keep the issue open because it's a valid concern.

**Comment by ztlevi** [comment]
Sure, thanks.

**Comment by Vifon** [comment]
I just realized I completely misunderstood you back then. I thought you want to bind the <kbd>PageDown</kbd> **key** to some action while you wanted to bind the `page_down` **action** to some key. In this case a <kbd>Ctrl</kbd> + some key. Yes, it is possible (though with <kbd>Alt</kbd> it wouldn't be). I think you need to use the literal `^D` character, for example by pressing <kbd>C-v</kbd> in Vim or <kbd>C-q</kbd> in Emacs and then <kbd>C-d</kbd>. It should do the trick, I just checked and it seems to work.
